### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by hoodsy** [faryon93/hlswatch#2]
Once I've configured hlswatch, how can I consume the viewer stats?

**Comment by faryon93** [comment]
The statistics are published in two different forms:

1. Written every second to an InfluxDB. A valid [influx] section must be present in the config file.
2. Exposed as an REST HTTP endpoint. The config entry common.listen specifies the address/port to listen on (e.g. 127.0.0.1:300). Then the JSON object containing the viewer information can be obtained at http://127.0.0.1:300/stats
